before_script:
  - echo "build docker babyy"

build_image:
  script:
    - docker build -rm -t cmer-csgo-server .
    - docker tag cmer-csgo-server tutum.co/cmer81/cssgo-server:latest 
    - docker push tutum.co/cmer81/cssgo-server:latest
    - docker rmi cmer-csgo-server
    - docker rmi tutum.co/cmer81/cssgo-server:latest